//include anywhere where the Ethereal Runes would be used

var simpleRunes = ["Ab", "Ai", "An", "Ao", "Ar", "Au",
                    "Be", "Bi", "Bo",
                    "Ca", "Co", "Cu",
                    "Da", "De", "Di",
                    "Ei", "El", "Ep", "Er", "Ev",
                    "Ia", "Ib", "Is", "Iv",
                    "Ga", "Go",
                    "Ha", "He",
                    "Ka", "Ke", "Ki",
                    "La", "Lu",
                    "Ma", "Me", "Mi",
                    "Na", "Ne", "Ni",
                    "Ob", "On", "Op",
                    "Pi", "Po",
                    "Ra", "Re", "Ri", "Ro", "Ru",
                    "Sa", "Se",
                    "Ta", "Te",
                    "Uv", "Ua",
                    "Va", "Vi", "Vo", "Vu",
                    "Za", "Ze", "Zi"];

var specialRunes = ["Bon", "Boq", "Bor",
                    "Cai", "Cao", "Cko", "Clu", "Cyar",
                    "Dan", "Dar", "Dis", "Dorg", "Dok", "Dox",
                    "Eje", "Eni",
                    "Gao",
                    "Hak", "Han", "Hel", "Hua", "Hva",
                    "Khe", "Kre",
                    "Lar",
                    "Mak", "Mal", "Mö",
                    "Nab", "Neo", "Nex", "Nos", "Nyk",
                    "Och", "Ota",
                    "Pel",
                    "Rea", "Rob", "Roi", "Rio", "Ris", "Ros",
                    "Sen", "Ses", "Shi", "Spi",
                    "Tem", "Tov", "Tzui",
                    "Vek", "Vel", "Voz",
                    "Ya",
                    "Xio", "Xy"];
